### PR TITLE
remove types and use acala-types.js instead

### PR DESCRIPTION
**Pull request by ermalkaleci**

### CODE REVIEW

**Review by ntduan — APPROVED** [review]

**Review by shunjizhan — APPROVED** [review]
LGTM, we can try it out

**Comment by shunjizhan** [comment]
@ntduan yeah when using this new version, we might need some updates on packages

**Comment by shunjizhan** [comment]
is there any tests to see how it goes? Like some basic tests to make sure the sdks still work with the new version

**Comment by ermalkaleci** [comment]
@ntduan no, this PR don't change any dependency. the one with polkadot 10 is on beta and it's 5.1.1-2

**Comment by ntduan** [comment]
> @ntduan no, this PR don't change any dependency. the one with polkadot 10 is on beta and it's 5.1.1-2

What I mean is that when we want to update acala.js, we have to update acala-types.js as well, and then now acala-types.js depends on polkadotjs 10, so we have to upgrade the polkadotjs that acala.js depends on to be updated to 10 as well in the next update.

**Review by ntduan — APPROVED** [review]

**Pull request merged**
